import type { ActiveBet, HistoryBet, Signal, SportKey } from "./types"

export const BANKROLL = 1247.3
export const FLAT_STAKE = 30

export const SIGNAL_TABS: { key: SportKey; label: string; sub: string }[] = [
  { key: "AGGREGATOR", label: "Agregatorius", sub: "Vertes galimybes" },
  { key: "NBA", label: "NBA", sub: "Kuriama" },
  { key: "PLAYER", label: "Zaidejai", sub: "Kuriama" },
  { key: "MLB", label: "MLB", sub: "Kuriama" },
  { key: "MBA", label: "MBA", sub: "Kuriama" },
]

export const SIGNALS: Signal[] = [
  // NBA
  {
    id: "nba-1",
    category: "NBA",
    sport: "NBA",
    match: "Boston Celtics @ Miami Heat",
    betDescription: "Celtics -5.5 (taskų skirtumas)",
    bookmaker: "TopSport",
    odds: 1.85,
    stake: 30,
    timeUntil: "2 val 14 min",
    confidence: 68,
    edgePercent: 7.4,
    kellyPercent: 2.6,
    rationale:
      "Celtics laimejo 8 is paskutiniu 10 svetur. Heat be Butler, gynybos reitingas krito i 14 vieta.",
  },
  {
    id: "nba-2",
    category: "NBA",
    sport: "NBA",
    match: "Denver Nuggets @ Phoenix Suns",
    betDescription: "Bendras taškų skaičius: Daugiau 228.5",
    bookmaker: "7BET",
    odds: 1.92,
    stake: 30,
    timeUntil: "3 val 40 min",
    confidence: 61,
    edgePercent: 4.1,
    kellyPercent: 1.4,
    rationale:
      "Abi komandos top-6 pagal tempa. Paskutiniai 5 tarpusavio rungtyniu virsijo bendra suma.",
  },
  {
    id: "nba-3",
    category: "NBA",
    sport: "NBA",
    match: "Milwaukee Bucks @ New York Knicks",
    betDescription: "Bucks moneyline",
    bookmaker: "TopSport",
    odds: 2.05,
    stake: 30,
    timeUntil: "5 val 05 min",
    confidence: 57,
    edgePercent: 3.2,
    kellyPercent: 1.1,
    rationale:
      "Modelis ivertina Bucks 54% laimejimo tikimybe; rinka per daug nuvertina po dvieju pralaimejimu.",
  },
  // Aggregator (kofai.lt style)
  {
    id: "agg-1",
    category: "AGGREGATOR",
    sport: "TENNIS",
    match: "Rinky Hijikata vs Alejandro Tabilo",
    betDescription: "Tabilo Alejandro geimu suminis: Daugiau 13",
    bookmaker: "TopSport",
    odds: 2.13,
    stake: 3,
    timeUntil: "57 min",
    confidence: 72,
    edgePercent: 8.5,
    kellyPercent: 2.1,
    rationale:
      "Pinnacle linija 2.34, TopSport siulo 2.13 — 8.5% verte lyginant su sharp knyga.",
    sharpOdds: 1.96,
    sharpBook: "Pinnacle",
  },
  {
    id: "agg-2",
    category: "AGGREGATOR",
    sport: "BASEBALL",
    match: "Boston Red Sox vs Toronto Blue Jays",
    betDescription: "R. Devers: Daugiau 1.5 bazes",
    bookmaker: "7BET",
    odds: 1.98,
    stake: 4,
    timeUntil: "1 val 20 min",
    confidence: 64,
    edgePercent: 5.7,
    kellyPercent: 1.8,
    rationale:
      "Devers pries desniarankius metikus muša .312. Sharp linija 1.84, 7BET 1.98.",
    sharpOdds: 1.84,
    sharpBook: "Pinnacle",
  },
  {
    id: "agg-3",
    category: "AGGREGATOR",
    sport: "BASKETBALL",
    match: "Reyer Venezia vs Olimpia Milano",
    betDescription: "Bendras taškų skaičius: Mažiau 158.5",
    bookmaker: "TopSport",
    odds: 1.91,
    stake: 3,
    timeUntil: "2 val 10 min",
    confidence: 66,
    edgePercent: 6.2,
    kellyPercent: 1.9,
    rationale:
      "Abi komandos žaidžia letą tempą. Pinnacle 1.78, TopSport 1.91 — aiški linijos verte.",
    sharpOdds: 1.78,
    sharpBook: "Pinnacle",
  },
  {
    id: "agg-4",
    category: "AGGREGATOR",
    sport: "SOCCER",
    match: "Argentina vs Algeria",
    betDescription: "Pirmas kelinys: Daugiau 0.5 ivarčio",
    bookmaker: "7BET",
    odds: 1.72,
    stake: 5,
    timeUntil: "3 val 30 min",
    confidence: 70,
    edgePercent: 4.9,
    kellyPercent: 1.6,
    rationale:
      "Argentina ataka pirmaisiais 45 min itin aktyvi; xG vidurkis 1.4 per pirma kelini.",
    sharpOdds: 1.64,
    sharpBook: "Pinnacle",
  },
  {
    id: "agg-5",
    category: "AGGREGATOR",
    sport: "TENNIS",
    match: "Brandon Nakashima vs Ignacio Buse",
    betDescription: "Nakashima geimu suminis: Daugiau 12.5",
    bookmaker: "TopSport",
    odds: 1.64,
    stake: 5,
    timeUntil: "16 val 49 min",
    confidence: 60,
    edgePercent: 1.1,
    kellyPercent: 0.5,
    rationale:
      "Fair koeficientas 1.62, TopSport siulo 1.64 — nedidele, bet stabili +1.1% verte.",
    sharpOdds: 1.55,
    sharpBook: "Pinnacle",
  },
  {
    id: "agg-6",
    category: "AGGREGATOR",
    sport: "BASKETBALL",
    match: "Indiana Fever vs Toronto Tempo",
    betDescription: "1-a puse tašku suminis: Mažiau 87.5",
    bookmaker: "7BET",
    odds: 1.95,
    stake: 4,
    timeUntil: "2 val 12 min",
    confidence: 63,
    edgePercent: 1.2,
    kellyPercent: 0.6,
    rationale:
      "Fair koeficientas 1.93, 7BET siulo 1.95. Letas pirmos puses tempas abiejose komandose.",
    sharpOdds: 1.83,
    sharpBook: "Pinnacle",
  },
  {
    id: "agg-7",
    category: "AGGREGATOR",
    sport: "BASEBALL",
    match: "Doosan Bears vs KT Wiz",
    betDescription: "Bendra suma: Daugiau 4.5",
    bookmaker: "7BET",
    odds: 1.87,
    stake: 4,
    timeUntil: "15 val 49 min",
    confidence: 58,
    edgePercent: 2.4,
    kellyPercent: 0.9,
    rationale:
      "KBO lygos vidurkis 9.1 tasko; abi komandos silpni starto metikai pries desniarankius.",
    sharpOdds: 1.79,
    sharpBook: "Pinnacle",
  },
  {
    id: "ply-1",
    category: "PLAYER",
    sport: "NBA",
    match: "Luka Dončič (DAL) vs MIN",
    betDescription: "Taškai: Daugiau 28.5",
    bookmaker: "TopSport",
    odds: 1.83,
    stake: 30,
    timeUntil: "4 val 00 min",
    confidence: 74,
    edgePercent: 9.1,
    kellyPercent: 2.8,
    rationale:
      "Dončič peržengė 28.5 tašku 7 is 10 paskutiniu rungtyniu. MIN leidžia daug taškų gynėjams.",
  },
  {
    id: "ply-2",
    category: "PLAYER",
    sport: "NBA",
    match: "Nikola Jokič (DEN) vs PHX",
    betDescription: "Atkovoti kamuoliai: Daugiau 12.5",
    bookmaker: "7BET",
    odds: 1.95,
    stake: 30,
    timeUntil: "3 val 40 min",
    confidence: 69,
    edgePercent: 6.8,
    kellyPercent: 2.2,
    rationale:
      "Jokič vidutiniškai 13.4 atkovotu kamuoliu; PHX silpni po krepšiu be centro.",
  },
  {
    id: "ply-3",
    category: "PLAYER",
    sport: "NBA",
    match: "Jayson Tatum (BOS) vs MIA",
    betDescription: "Rez. perdavimai: Mažiau 4.5",
    bookmaker: "TopSport",
    odds: 1.88,
    stake: 30,
    timeUntil: "2 val 14 min",
    confidence: 60,
    edgePercent: 3.6,
    kellyPercent: 1.2,
    rationale:
      "Tatum daugiau metimo orientuotas pries MIA zonine gynyba; perdavimu vidurkis krenta.",
  },
  // MLB
  {
    id: "mlb-1",
    category: "MLB",
    sport: "MLB",
    match: "Arizona Diamondbacks @ Los Angeles Angels",
    betDescription: "Diamondbacks moneyline",
    bookmaker: "7BET",
    odds: 1.96,
    stake: 30,
    timeUntil: "6 val 30 min",
    confidence: 63,
    edgePercent: 5.0,
    kellyPercent: 1.7,
    rationale:
      "Gallen (2.41 ERA) pries silpna Angels rikiuote. Modelis duoda 56% laimejimo tikimybe.",
  },
  {
    id: "mlb-2",
    category: "MLB",
    sport: "MLB",
    match: "New York Yankees @ Houston Astros",
    betDescription: "Bendras taškų skaičius: Mažiau 8.5",
    bookmaker: "TopSport",
    odds: 1.9,
    stake: 30,
    timeUntil: "7 val 05 min",
    confidence: 58,
    edgePercent: 3.4,
    kellyPercent: 1.1,
    rationale:
      "Du top metikai pries vienas kita; vejas pučia i aikšte, slopina lekiojancius kamuolius.",
  },
  // MBA
  {
    id: "mba-1",
    category: "MBA",
    sport: "BASKETBALL",
    match: "Gonzaga vs Saint Mary's",
    betDescription: "Gonzaga -6.5",
    bookmaker: "TopSport",
    odds: 1.87,
    stake: 30,
    timeUntil: "8 val 00 min",
    confidence: 65,
    edgePercent: 5.5,
    kellyPercent: 1.9,
    rationale:
      "Gonzaga namuose +12.3 taško vidurkis; Saint Mary's puolimo efektyvumas 0.98 PPP.",
  },
  {
    id: "mba-2",
    category: "MBA",
    sport: "BASKETBALL",
    match: "Duke vs North Carolina",
    betDescription: "Bendras taškų skaičius: Daugiau 152.5",
    bookmaker: "7BET",
    odds: 1.93,
    stake: 30,
    timeUntil: "9 val 15 min",
    confidence: 62,
    edgePercent: 4.3,
    kellyPercent: 1.4,
    rationale:
      "Greitas derbio tempas; paskutiniai 4 tarpusavio susitikimai virsijo 150 tašku riba.",
  },
]

export const INITIAL_ACTIVE_BETS: ActiveBet[] = [
  // Pre-placed bets that share a match with live signals, so the
  // "Jau statei šiose rungtynėse" panel has something to show.
  {
    id: "act-0a",
    signalId: "seed-fever-1",
    sport: "BASKETBALL",
    match: "Indiana Fever vs Toronto Tempo",
    betDescription: "Suminis (+OT): Daugiau 178.5",
    bookmaker: "7BET",
    odds: 1.93,
    stake: 3,
    status: "laukia",
    placedAt: "Šiandien 12:40",
    profit: null,
  },
  {
    id: "act-0b",
    signalId: "seed-fever-2",
    sport: "BASKETBALL",
    match: "Indiana Fever vs Toronto Tempo",
    betDescription: "1-a rungt. pusė: Indiana Fever",
    bookmaker: "TopSport",
    odds: 1.53,
    stake: 6,
    status: "laukia",
    placedAt: "Šiandien 12:38",
    profit: null,
  },
  {
    id: "act-1",
    signalId: "seed-1",
    sport: "TENNIS",
    match: "Ben Shelton vs Lorenzo Sonego",
    betDescription: "Setu suminis: Daugiau 2.5",
    bookmaker: "TopSport",
    odds: 1.95,
    stake: 30,
    status: "laukia",
    placedAt: "Šiandien 14:20",
    profit: null,
  },
  {
    id: "act-2",
    signalId: "seed-2",
    sport: "NBA",
    match: "LA Lakers @ Golden State",
    betDescription: "Warriors -3.5",
    bookmaker: "7BET",
    odds: 1.88,
    stake: 30,
    status: "laukia",
    placedAt: "Šiandien 13:02",
    profit: null,
  },
  {
    id: "act-3",
    signalId: "seed-3",
    sport: "BASEBALL",
    match: "Dodgers @ Padres",
    betDescription: "Bendra suma: Mažiau 7.5",
    bookmaker: "TopSport",
    odds: 1.91,
    stake: 30,
    status: "laimeta",
    placedAt: "Šiandien 11:45",
    profit: 27.3,
  },
  {
    id: "act-4",
    signalId: "seed-4",
    sport: "SOCCER",
    match: "Real Madrid vs Sevilla",
    betDescription: "Abi komandos pelnys: Taip",
    bookmaker: "7BET",
    odds: 1.78,
    stake: 30,
    status: "pralaimeta",
    placedAt: "Šiandien 10:10",
    profit: -30,
  },
]

export const HISTORY: HistoryBet[] = [
  { id: "h1", date: "2026-06-15", sport: "NBA", match: "Celtics @ Nets", betDescription: "Celtics -7.5", bookmaker: "TopSport", odds: 1.9, stake: 30, status: "laimeta", profit: 27 },
  { id: "h2", date: "2026-06-15", sport: "TENNIS", match: "Alcaraz vs Rune", betDescription: "Alcaraz 2:0", bookmaker: "7BET", odds: 2.1, stake: 30, status: "pralaimeta", profit: -30 },
  { id: "h3", date: "2026-06-14", sport: "MLB", match: "Yankees @ Red Sox", betDescription: "Daugiau 9.5", bookmaker: "TopSport", odds: 1.95, stake: 30, status: "laimeta", profit: 28.5 },
  { id: "h4", date: "2026-06-14", sport: "BASKETBALL", match: "Duke vs UNC", betDescription: "Duke -4.5", bookmaker: "7BET", odds: 1.87, stake: 30, status: "laimeta", profit: 26.1 },
  { id: "h5", date: "2026-06-13", sport: "SOCCER", match: "Arsenal vs Chelsea", betDescription: "Daugiau 2.5", bookmaker: "TopSport", odds: 1.8, stake: 30, status: "pralaimeta", profit: -30 },
  { id: "h6", date: "2026-06-13", sport: "NBA", match: "Suns @ Nuggets", betDescription: "Jokič 12.5+ atk.", bookmaker: "7BET", odds: 1.95, stake: 30, status: "laimeta", profit: 28.5 },
  { id: "h7", date: "2026-06-12", sport: "BASEBALL", match: "Dbacks @ Angels", betDescription: "Dbacks ML", bookmaker: "TopSport", odds: 1.96, stake: 30, status: "laimeta", profit: 28.8 },
  { id: "h8", date: "2026-06-12", sport: "TENNIS", match: "Sinner vs Medvedev", betDescription: "Daugiau 22.5 geimu", bookmaker: "TopSport", odds: 1.85, stake: 30, status: "pralaimeta", profit: -30 },
  { id: "h9", date: "2026-06-11", sport: "NBA", match: "Heat @ Bucks", betDescription: "Bucks ML", bookmaker: "7BET", odds: 1.7, stake: 30, status: "laimeta", profit: 21 },
  { id: "h10", date: "2026-06-11", sport: "MLB", match: "Mets @ Braves", betDescription: "Mažiau 8.5", bookmaker: "TopSport", odds: 1.92, stake: 30, status: "grazinta", profit: 0 },
  { id: "h11", date: "2026-06-10", sport: "TENNIS", match: "Zverev vs Ruud", betDescription: "Zverev 2:1", bookmaker: "TopSport", odds: 2.2, stake: 30, status: "laimeta", profit: 36 },
  { id: "h12", date: "2026-06-10", sport: "NBA", match: "Clippers @ Kings", betDescription: "Daugiau 224.5", bookmaker: "7BET", odds: 1.91, stake: 30, status: "pralaimeta", profit: -30 },
  { id: "h13", date: "2026-06-09", sport: "BASKETBALL", match: "Gonzaga vs Saint Mary's", betDescription: "Gonzaga -6.5", bookmaker: "TopSport", odds: 1.87, stake: 30, status: "laimeta", profit: 26.1 },
  { id: "h14", date: "2026-06-09", sport: "MLB", match: "Astros @ Rangers", betDescription: "Astros ML", bookmaker: "7BET", odds: 1.74, stake: 30, status: "laimeta", profit: 22.2 },
  { id: "h15", date: "2026-06-08", sport: "SOCCER", match: "Bayern vs Dortmund", betDescription: "Daugiau 3.5", bookmaker: "TopSport", odds: 2.05, stake: 30, status: "pralaimeta", profit: -30 },
  { id: "h16", date: "2026-06-08", sport: "TENNIS", match: "Swiatek vs Gauff", betDescription: "Mažiau 21.5 geimu", bookmaker: "7BET", odds: 1.9, stake: 30, status: "laimeta", profit: 27 },
  { id: "h17", date: "2026-06-07", sport: "NBA", match: "Lakers @ Suns", betDescription: "Davis 11.5+ atk.", bookmaker: "7BET", odds: 1.83, stake: 30, status: "laimeta", profit: 24.9 },
  { id: "h18", date: "2026-06-06", sport: "MLB", match: "Yankees @ Orioles", betDescription: "Mažiau 9.5", bookmaker: "TopSport", odds: 1.95, stake: 30, status: "pralaimeta", profit: -30 },
  { id: "h19", date: "2026-06-05", sport: "BASKETBALL", match: "Duke vs Kansas", betDescription: "Daugiau 148.5", bookmaker: "TopSport", odds: 1.88, stake: 30, status: "laimeta", profit: 26.4 },
  { id: "h20", date: "2026-06-04", sport: "SOCCER", match: "PSG vs Lyon", betDescription: "PSG -1.5", bookmaker: "7BET", odds: 1.96, stake: 30, status: "laimeta", profit: 28.8 },
  { id: "h21", date: "2026-06-03", sport: "TENNIS", match: "Djokovic vs Tsitsipas", betDescription: "Djokovic 2:0", bookmaker: "7BET", odds: 1.8, stake: 30, status: "pralaimeta", profit: -30 },
  { id: "h22", date: "2026-06-02", sport: "NBA", match: "Bucks @ Celtics", betDescription: "Mažiau 219.5", bookmaker: "TopSport", odds: 1.92, stake: 30, status: "laimeta", profit: 27.6 },
  { id: "h23", date: "2026-06-01", sport: "MLB", match: "Dodgers @ Giants", betDescription: "Dodgers ML", bookmaker: "7BET", odds: 1.7, stake: 30, status: "laimeta", profit: 21 },
]
